[build]
  publish = "."
  functions = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"

[[redirects]]
  from = "/api/redeem"
  to = "/.netlify/functions/redeem"
  status = 200
  
[[redirects]]
  from = "/api/*"
  to = "https://backend-o9ot.onrender.com/api/:splat"
  status = 200
  force = true
